#!/usr/bin/env bash
# =============================================================================
# sync-agent-files.sh — generate per-directory CLAUDE.md entry points
# =============================================================================
# AGENTS.md is the source of truth for agent guidance (read natively by
# Antigravity/agy and other modern CLI agents). Claude Code reads CLAUDE.md,
# so every directory holding an AGENTS.md gets a generated thin CLAUDE.md
# containing an @AGENTS.md import. Generated files, not symlinks — symlinks
# break on Windows checkouts, IDE agent checkouts, and zip exports.
#
# Idempotent; run after adding or moving any AGENTS.md:
#   scripts/sync-agent-files.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

sync_dir() {
  local dir="$1"
  [ -f "$dir/AGENTS.md" ] || return 0

  cat > "$dir/CLAUDE.md" <<'EOF'
# CLAUDE.md

<!-- GENERATED by scripts/sync-agent-files.sh — edit AGENTS.md, not this file. -->

@AGENTS.md
EOF
  echo "wrote $dir/CLAUDE.md"

  # Legacy GEMINI.md files are superseded — agy reads AGENTS.md natively.
  if [ -f "$dir/GEMINI.md" ]; then
    rm -f "$dir/GEMINI.md"
    echo "removed legacy $dir/GEMINI.md"
  fi
}

cd "$REPO_ROOT"
while IFS= read -r -d '' f; do
  sync_dir "$(dirname "$f")"
done < <(find . -name AGENTS.md -not -path './.git/*' -not -path './docs/_archive/*' -print0)

echo "agent entry-point sync complete."
